buildscript {
	repositories {
		mavenCentral()
		maven { url "https://maven.fabricmc.net" }
		maven { url "https://repo.sleeping.town" } //Commented out to use the version of voldeloom in the settings.gradle includeBuild (hopefully??)
	}
	dependencies {
		classpath "agency.highlysuspect:voldeloom:2.4-SNAPSHOT"
	}
}

apply plugin: "agency.highlysuspect.voldeloom"
// make sure SKD is set to 11
java.toolchain.languageVersion = JavaLanguageVersion.of(11) //Last version able to set a --release as low as 6
compileJava.options.release.set(6) //Forge doesn't understand classes compiled to versions of the class-file format newer than Java 6's

String minecraftVersion = project.minecraft
String forgeVersion = project.minecraft_forge
archivesBaseName = project.modid
version = project.modVersion

volde {
	forgeCapabilities {
		srgsAsFallback = true
	}

	runs {
		client {
			programArg "quaternary"
		}
	}
}

dependencies {
	implementation 'net.jcip:jcip-annotations:1.0'
	implementation 'org.jetbrains:annotations-java5:23.0.0'
    minecraft "com.mojang:minecraft:${minecraftVersion}"
	forge "net.minecraftforge:forge:${forgeVersion}:universal@zip"

	mappings volde.layered {
		importBaseZip "net.minecraftforge:forge:${forgeVersion}:src@zip"
		removeClasses(["bar", "bas"])
	}

	modImplementation files("libs/industrialcraft-2_1.115.207-lf.jar")
	modImplementation files("libs/appeng-rv9-i.zip")
	modImplementation files("libs/gregtechmod290h.zip")
	modImplementation files("libs/VintageCore-1.4.7-2.0.1-dev.jar")
}

def props = ['modName', 'modid', 'modVersion', 'modDescription', 'modAuthors', 'modDeps', 'minecraft', 'url']
processResources {
	filesMatching("mcmod.info") {
		expand(project.properties.subMap(props))
	}
}

sourceSets {
	main {
		resources {
			srcDirs 'src/main/java'
		}
	}
}

task sourcesJar(type: Jar) {
	archiveClassifier.set("sources")
	from sourceSets.main.allSource

}

artifacts {
	archives sourcesJar
}

jar {
	exclude ("**/com/**")
}



