# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
modName = GraviSuite - Addon
modid = gravisuite
modVersion = 1.6.4-2.2.2.9
modDescription = A powerful IndustrialCraft 2 addon that allows you to fly and introduces advanced tools to boost your mining and harvesting efficiency.
modAuthors = Original: SeNtiMeL, Reforged: CrossVas
modDeps = required-after:VintageCore;required-after:IC2;after:GregTech_Addon
url = https://github.com/VintageModsReforged/GraviSuiteReforged

minecraft = 1.6.4
minecraft_forge = 1.6.4-9.11.1.1345